import Layout from "@/components/Layout";
import { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <Layout>
      <main>Home page</main>
    </Layout>
  );
}
